package me.coolaid.optical.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.BooleanControllerBuilder;
import dev.isxander.yacl3.api.controller.DoubleSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.util.List;

public class ConfigScreen {
    private static final List<Integer> LIMITS = List.of(30, 60, 90, 360);

    public static Screen create(Screen parent) {
        OpticalConfig.ensureBrightnessLoaded();
        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("optical.config.title"))

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("optical.category.general"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("optical.general.group.misc"))
                                .collapsed(false)
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.literal("Placeholder Option"))
                                        .description(OptionDescription.of(Component.literal("Placeholder Option Description")))
                                        .binding(false, () -> false, value -> {
                                        })
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("optical.general.group.freelook"))
                                .collapsed(false)
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.freelook.option.enabled"))
                                        .description(OptionDescription.of(Component.translatable("optical.freelook.option.enabled.desc")))
                                        .binding(true, OpticalConfig.FREELOOK::isEnabled, OpticalConfig.FREELOOK::setEnabled)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.freelook.option.invert"))
                                        .description(OptionDescription.of(Component.translatable("optical.freelook.option.invert.desc")))
                                        .binding(true, OpticalConfig.FREELOOK::isInvertY, OpticalConfig.FREELOOK::setInvertY)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.freelook.option.toggle_mode"))
                                        .description(OptionDescription.of(Component.translatable("optical.freelook.option.toggle_mode.desc")))
                                        .binding(false, OpticalConfig.FREELOOK::isToggleMode, OpticalConfig.FREELOOK::setToggleMode)
                                        .controller(opt -> BooleanControllerBuilder.create(opt)
                                                .formatValue(val -> val ? Component.translatable("optical.freelook.value.toggle") : Component.translatable("optical.freelook.value.hold")))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.freelook.option.sensitivity"))
                                        .description(OptionDescription.of(Component.translatable("optical.freelook.option.sensitivity.desc")))
                                        .binding(1.0D, OpticalConfig.FREELOOK::getSensitivityMultiplier, OpticalConfig.FREELOOK::setSensitivityMultiplier)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.1D, 2.0D).step(0.05D).formatValue(val -> Component.literal(String.format("%.2fx", val))))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("optical.freelook.option.limit"))
                                        .description(OptionDescription.of(Component.translatable("optical.freelook.option.limit.desc")))
                                        .binding(3, () -> {
                                            int index = LIMITS.indexOf(OpticalConfig.FREELOOK.getRotationLimit());
                                            return index != -1 ? index : 3;
                                        }, index -> OpticalConfig.FREELOOK.setRotationLimit(LIMITS.get(index)))
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, LIMITS.size() - 1)
                                                .step(1)
                                                .formatValue(index -> {
                                                    int value = LIMITS.get(index);
                                                    return Component.literal(value == 360 ? "360° (Full)" : value + "°");
                                                }))
                                        .build())
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("optical.category.freecam"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("optical.freecam.option.enabled"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.enabled.desc")))
                                .binding(true, OpticalConfig.FREECAM::isEnabled, OpticalConfig.FREECAM::setEnabled)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("optical.freecam.option.invert"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.invert.desc")))
                                .binding(false, OpticalConfig.FREECAM::isInvertY, OpticalConfig.FREECAM::setInvertY)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("optical.freecam.option.sensitivity"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.sensitivity.desc")))
                                .binding(1.0D, OpticalConfig.FREECAM::getSensitivityMultiplier, OpticalConfig.FREECAM::setSensitivityMultiplier)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.1D, 4.0D).step(0.05D).formatValue(val -> Component.literal(String.format("%.2fx", val))))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("optical.freecam.option.momentum_default"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.momentum_default.desc")))
                                .binding(false, OpticalConfig.FREECAM::isMomentumByDefault, OpticalConfig.FREECAM::setMomentumByDefault)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("optical.freecam.option.horizontal_speed"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.horizontal_speed.desc")))
                                .binding(0.8D, OpticalConfig.FREECAM::getHorizontalSpeed, OpticalConfig.FREECAM::setHorizontalSpeed)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.05D, 8.0D).step(0.05D).formatValue(val -> Component.literal(String.format("%.2f", val))))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("optical.freecam.option.vertical_speed"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.vertical_speed.desc")))
                                .binding(0.6D, OpticalConfig.FREECAM::getVerticalSpeed, OpticalConfig.FREECAM::setVerticalSpeed)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.05D, 8.0D).step(0.05D).formatValue(val -> Component.literal(String.format("%.2f", val))))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("optical.freecam.option.momentum_smoothing"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.momentum_smoothing.desc")))
                                .binding(0.25D, OpticalConfig.FREECAM::getMomentumSmoothing, OpticalConfig.FREECAM::setMomentumSmoothing)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.05D, 1.0D).step(0.05D).formatValue(val -> Component.literal(String.format("%.2f", val))))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("optical.freecam.option.momentum_damping"))
                                .description(OptionDescription.of(Component.translatable("optical.freecam.option.momentum_damping.desc")))
                                .binding(0.9D, OpticalConfig.FREECAM::getMomentumDamping, OpticalConfig.FREECAM::setMomentumDamping)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.1D, 0.99D).step(0.01D).formatValue(val -> Component.literal(String.format("%.2f", val))))
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("optical.category.zoom"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("optical.zoom.group.basic"))
                                .collapsed(false)
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.enabled"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.enabled.desc")))
                                        .binding(true, OpticalConfig.ZOOM::isEnabled, OpticalConfig.ZOOM::setEnabled)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.default_strength"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.default_strength.desc")))
                                        .binding(3.0D, OpticalConfig.ZOOM::getDefaultZoomStrength, OpticalConfig.ZOOM::setDefaultZoomStrength)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(1.0D, 10.0D)
                                                .step(1.0D)
                                                .formatValue(val -> Component.literal(String.format("%.0fx", val))))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.zoom_in_transition"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.zoom_in_transition.desc")))
                                        .binding(false,
                                                () -> OpticalConfig.ZOOM.getZoomInTransition() == OpticalConfig.ZoomConfig.TransitionMode.INSTANT,
                                                val -> OpticalConfig.ZOOM.setZoomInTransition(val ? OpticalConfig.ZoomConfig.TransitionMode.INSTANT : OpticalConfig.ZoomConfig.TransitionMode.EXPONENTIAL))
                                        .controller(opt -> BooleanControllerBuilder.create(opt)
                                                .formatValue(val -> val
                                                        ? Component.translatable("optical.zoom.value.instant")
                                                        : Component.translatable("optical.zoom.value.exponential")))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.zoom_out_transition"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.zoom_out_transition.desc")))
                                        .binding(false,
                                                () -> OpticalConfig.ZOOM.getZoomOutTransition() == OpticalConfig.ZoomConfig.TransitionMode.INSTANT,
                                                val -> OpticalConfig.ZOOM.setZoomOutTransition(val ? OpticalConfig.ZoomConfig.TransitionMode.INSTANT : OpticalConfig.ZoomConfig.TransitionMode.EXPONENTIAL))
                                        .controller(opt -> BooleanControllerBuilder.create(opt)
                                                .formatValue(val -> val
                                                        ? Component.translatable("optical.zoom.value.instant")
                                                        : Component.translatable("optical.zoom.value.exponential")))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.zoom_in_seconds"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.zoom_in_seconds.desc")))
                                        .binding(1.0D, OpticalConfig.ZOOM::getZoomInSeconds, OpticalConfig.ZOOM::setZoomInSeconds)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.1D, 5.0D)
                                                .step(0.1D)
                                                .formatValue(val -> Component.literal(String.format("%.1fs", val))))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.zoom_out_seconds"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.zoom_out_seconds.desc")))
                                        .binding(0.5D, OpticalConfig.ZOOM::getZoomOutSeconds, OpticalConfig.ZOOM::setZoomOutSeconds)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.1D, 5.0D)
                                                .step(0.1D)
                                                .formatValue(val -> Component.literal(String.format("%.1fs", val))))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("optical.zoom.group.scrolling"))
                                .collapsed(false)
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.scroll"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.scroll.desc")))
                                        .binding(true, OpticalConfig.ZOOM::isScrollAdjustEnabled, OpticalConfig.ZOOM::setScrollAdjustEnabled)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.scroll_smoothness"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.scroll_smoothness.desc")))
                                        .binding(70, OpticalConfig.ZOOM::getScrollZoomSmoothness, OpticalConfig.ZOOM::setScrollZoomSmoothness)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 100)
                                                .step(1)
                                                .formatValue(val -> Component.literal(val + "%")))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.scroll_step_count"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.scroll_step_count.desc")))
                                        .binding(10, OpticalConfig.ZOOM::getScrollStepCount, OpticalConfig.ZOOM::setScrollStepCount)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(1, 50)
                                                .step(1))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.zoom_per_step"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.zoom_per_step.desc")))
                                        .binding(1.5D, OpticalConfig.ZOOM::getZoomPerStep, OpticalConfig.ZOOM::setZoomPerStep)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(1.05D, 3.0D)
                                                .step(0.05D)
                                                .formatValue(val -> Component.literal(String.format("%.2fx", val))))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.remember_steps"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.remember_steps.desc")))
                                        .binding(false, OpticalConfig.ZOOM::isRememberZoomSteps, OpticalConfig.ZOOM::setRememberZoomSteps)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("optical.zoom.group.secondary"))
                                .collapsed(false)
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.secondary_strength"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.secondary_strength.desc")))
                                        .binding(3.0D, OpticalConfig.ZOOM::getSecondaryZoomStrength, OpticalConfig.ZOOM::setSecondaryZoomStrength)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(1.0D, 10.0D)
                                                .step(1.0D)
                                                .formatValue(val -> Component.literal(String.format("%.1fx", val))))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.secondary_zoom_in_seconds"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.secondary_zoom_in_seconds.desc")))
                                        .binding(10.0D, OpticalConfig.ZOOM::getSecondaryZoomInSeconds, OpticalConfig.ZOOM::setSecondaryZoomInSeconds)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.1D, 60.0D)
                                                .step(0.1D)
                                                .formatValue(val -> Component.literal(String.format("%.1fs", val))))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("optical.zoom.option.secondary_zoom_out_seconds"))
                                        .description(OptionDescription.of(Component.translatable("optical.zoom.option.secondary_zoom_out_seconds.desc")))
                                        .binding(1.0D, OpticalConfig.ZOOM::getSecondaryZoomOutSeconds, OpticalConfig.ZOOM::setSecondaryZoomOutSeconds)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt)
                                                .range(0.1D, 60.0D)
                                                .step(0.1D)
                                                .formatValue(val -> Component.literal(String.format("%.1fs", val))))
                                        .build())
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("optical.category.gamma"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("optical.gamma.option.enabled"))
                                .description(OptionDescription.of(Component.translatable("optical.gamma.option.enabled.desc")))
                                .binding(true, OpticalConfig.BRIGHTNESS::isEnabled, OpticalConfig.BRIGHTNESS::setEnabled)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("optical.gamma.option.default"))
                                .description(OptionDescription.of(Component.translatable("optical.gamma.option.default.desc")))
                                .binding(100, OpticalConfig.BRIGHTNESS::getDefaultLevel, OpticalConfig.BRIGHTNESS::setDefaultLevel)
                                .controller(IntegerFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("optical.gamma.option.toggled"))
                                .description(OptionDescription.of(Component.translatable("optical.gamma.option.toggled.desc")))
                                .binding(1500, OpticalConfig.BRIGHTNESS::getToggledLevel, OpticalConfig.BRIGHTNESS::setToggledLevel)
                                .controller(IntegerFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("optical.gamma.option.step"))
                                .description(OptionDescription.of(Component.translatable("optical.gamma.option.step.desc")))
                                .binding(10, OpticalConfig.BRIGHTNESS::getGammaStep, OpticalConfig.BRIGHTNESS::setGammaStep)
                                .controller(IntegerFieldControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("optical.gamma.option.update_toggle_value"))
                                .description(OptionDescription.of(Component.translatable("optical.gamma.option.update_toggle_value.desc")))
                                .binding(true, OpticalConfig.BRIGHTNESS::isUpdateToggleValue, OpticalConfig.BRIGHTNESS::setUpdateToggleValue)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("optical.gamma.option.show_message"))
                                .description(OptionDescription.of(Component.translatable("optical.gamma.option.show_message.desc")))
                                .binding(true, OpticalConfig.BRIGHTNESS::isShowGammaMessage, OpticalConfig.BRIGHTNESS::setShowGammaMessage)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .build())

                .build()
                .generateScreen(parent);
    }
}